runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')

## ---(Wed Jul 24 14:07:52 2019)---
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(serialPort.readline())
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(serialPort.readline().type)
print(type(data))
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
sum(corrected)
1000 * corrected[1] + 2000 * corrected[2] + 3000* corrected[3] + 4000 * corrected[4]
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
0 * corrected[0] + 1000 * corrected[1] + 2000 * corrected[2] + 3000 * corrected[3] + 4000 * corrected[4]
0 * corrected[0] + 1000 * corrected[1] + 2000 * corrected[2] + 3000 * corrected[3] + 4000 * corrected[4] / ( sum(corrected))
sum(corrected)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(min)
print(minn)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(minn)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(minn)
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(0.0045662104456221 * 0)
print(.9714611872146118 * 1000)
print(.9988584474885844 * 2000)
print(.997716894977169 * 3000)
print (.9840182648401826 * 4000)
(971.4611872146119  + 1997.716894977169 + 2993.150684931507 + 3936.0730593607304)
9898.40182648402/(4000)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
sum(corrected)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
myserialPort.close()
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
print(minn)
print(maxx)
split_data[0] - minn / ( maxx - minn) 
int(split_data[0]) - minn / ( maxx - minn)
split_data[1] - minn / ( maxx - minn)
int(split_data[1] - minn / ( maxx - minn))
int(split_data[1] )- minn / ( maxx - minn)
int(split_data[2] )- minn / ( maxx - minn)
int(split_data[3] )- minn / ( maxx - minn)
int(split_data[4] )- minn / ( maxx - minn)
print(corrected[0])
int((split_data[1] )- minn) / ( maxx - minn)
(int(split_data[1] )- minn )/ ( maxx - minn)
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
serialPort.close()
runfile('C:/Users/ezhu2/.spyder-py3/untitled0.py', wdir='C:/Users/ezhu2/.spyder-py3')
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')
serialPort.close()
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')
serialPort.close()
serialPort2.close()
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')
serialPort2.close()
serialPort.close()
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')
serialPort.close()
serialPort2.close()
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')
serialPort.close()
serialPort2.close()
runfile('C:/Users/ezhu2/two test.py', wdir='C:/Users/ezhu2')